### ISSUE TITLE
E-Mail für Kontaktformular oder Fragen aufsetzten

### ISSUE THREAD

**Issue by lorey** [lorey/roadgenius.de#1]
Die im Kontaktformular angegebene E-Mail sollte aufgesetzt werden: mail@roadgenius.de

Kontaktformular: https://github.com/lorey/roadgenius.de/blob/master/mail/contact_me.php

**Comment by lockeyo** [comment]
Kannst du mir vielleicht helfen eine Email Server aufzusetzen? Habe da immer meine Schwirigkweiten.

**Comment by lorey** [comment]
Einfachere Möglichkeit wäre gmail mit Weiterleitung an uns alle.

**Comment by lockeyo** [comment]
Ja, dass kann ich heute Abend einrichten

**Comment by lorey** [comment]
Perfekt :+1:

**Comment by lorey** [comment]
@lockeyo done?

**Comment by lockeyo** [comment]
Not now. I'm going to do it in a minute or so. Sorry. Had to do some things for the DHBW.

**Comment by lorey** [comment]
No problem. I just received a mail from one of the mentors and got reminded of this as he surely tried the one on roadgenius.de, too. I will forward it to you later.

**Comment by lockeyo** [comment]
Done, but not tested. Seems there is a problem with google groups, but i will take a lock. If it's not working for you just let me know and i will post every mail i get.
