### ISSUE TITLE
Add SSL-Certificate to the website

### ISSUE THREAD

**Issue by lockeyo** [lorey/roadgenius.de#11]
it would be nice to have a SSL-Certificate for the website to make sure everything is encrypted and we can  show our users that we are a trusted source.

**Comment by lockeyo** [comment]
Do anyone have any experience with SSL-Certificates.
There are so many companys offer this service. 
- Comodo (https://ssl.comodo.com/comodo-ssl-certificate.php)
- GeoTrust (https://www.geotrust.com/de/ssl/)
- RapidSSL (https://www.rapidssl.com/)

Would be awesome if some could help.

**Comment by TobiasWeis** [comment]
comodo ist ein re-seller, scheint aber auch oft benutzt zu werden...ich würde jetzt für den Start erstmal eins von denen nehmen, 100€ scheint mir auch ganz ok

**Comment by lorey** [comment]
Comodo: http://www.theregister.co.uk/2015/02/24/comodo_ssl_privdog/

**Comment by lockeyo** [comment]
SSL is active on Road Genius now.
