### ISSUE TITLE
One Pager - Abgabe wäre heute um 12 Uhr gewesen

### ISSUE THREAD

**Issue by lorey** [lorey/roadgenius.de#13]
Haben vergessen uns um den Fragebogen zu kümmern. Der hätte heute um 12 Uhr abgegeben werden müssen, die Frage ist wo. Folgende Fragen sind zu beantworten:

* Die Problemstellung
* Lösung > ggf. Alleinstellungsmerkmal
* Business Model > Monetarisierung
* Eure Ziel- / Anspruchsgruppen
* Wettbewerbsvorteil eures Produkts
* Euer Management Team
* Grobe Finanzierung

Habe leider gerade keine Zeit wegen dem Seminar. Wäre gut, wenn ihr euch dazu mal was überlegen könntet bis nachher.

**Comment by lockeyo** [comment]
Ich versuche etwas vorzubereiten. Allerdings würde ich das gerne in einem privaten Repo machen. Hier kann jeder lesen. Ich schlafe vor wir arbeiten zusammen unter  https://github.com/lockeyo/RoadGenius-Server/wiki/Business-Plan-(German)

**Comment by lorey** [comment]
Alles klar!
