### ISSUE TITLE
Update repository with current website version

### ISSUE THREAD

**Issue by lorey** [lorey/roadgenius.de#14]
@lockeyo Your design is neither in the roadgenius.de nor in the community repo. Could you update the repo, please? It would be sufficient if you just update the roadgenius.de repo. In Laravel, it is highly duplicated at the moment. I'm going to clean this up and pull it into laravel afterwards.

**Comment by lockeyo** [comment]
I#m going to move the files to the Road Genius Community Repo and do the update. I think it's easier to keep one repo on the current state instead of two.
