### ISSUE TITLE
SEO-Überlegungen

### ISSUE THREAD

**Issue by lorey** [lorey/roadgenius.de#4]
Wir wollen bei google gefunden werden. Dazu folgende Ideen:
* Alle Artikel bitten die URL zu verlinken
* Twitter-Account: Hashtag-Monitoring (langeweile, auto, kinder?)
* Auf Facebook möglichst immer die URL posten
* Bei allen Möglichkeiten nicht von Road Genius sondern von RoadGenius.de sprechen
* Sich klar über die Keywords werden (Quiz, App, Kinder, Langeweile, Auto, Fahrt)

Bin auf eure Ideen und Kommentare gespannt.

**Comment by lockeyo** [comment]
Werde mal gleich (ab 21.00 Uhr) meine SEO Skills auspacken. Habe bisher jede Seite auf Platz eins gebracht.
Meine Ideen Erstmal. (Wordpress) Blog aufsetzen und Artikel schreiben die die Keywords beinhalten.

- Facebook Seite kann ich anlegen oder wer anderes. Dafür brauchen wir dann 25 Likes um die Seite dann auf facebook.com/roadgenius zu mappen. 

- Twitter Acc erstellen 

Keywords: Kinderquiz Community, Ortsbasiertes Quiz, Auto Quiz, Autofahrt, Fahrsicherheit

**Comment by lorey** [comment]
Lass uns das bitte koordiniert machen. Warum heute um 21 Uhr? Wäre es nicht sinnvoller zunächst eine gut spielbare Version der App fertig zu bekommen und online zu stellen? Ich denke, wir sollten da klare Prioritäten setzen. Erst mal Content, dann die Optimierung.

Wenn wir die erste fertige Version haben, sind wir uns wahrscheinlich auch mit den Keywords und ähnlichem einig. Einen Blog müsste ich eh in die Community integrieren und würde mich gerne darum kümmern. Aber first things first...

**Comment by lockeyo** [comment]
RoadGenius.de has hit the first page of  the google results. We are on the 10th search result of google.de with the keyword "roadgenius". I hope we're on first place within the next week.

**Comment by lorey** [comment]
Should be sufficient for now...
