### ISSUE TITLE
Copy images to our server

### ISSUE THREAD

**Issue by lorey** [lorey/roadgenius.de#5]
Stop usage of hotlinking for pictures, especially images of team members and logos.

**Comment by lockeyo** [comment]
Done!

**Comment by lorey** [comment]
Thanks, but your picture is gone.

**Comment by lockeyo** [comment]
Had a " at the end. Fixed.

**Comment by lorey** [comment]
World map image is now missing in the repo...

**Comment by lockeyo** [comment]
Sorry. Fixed.
