### ISSUE TITLE
To www or not to www

### ISSUE THREAD

**Issue by lorey** [lorey/roadgenius.de#6]
Best practice ist m.E. www, aber da scheiden sich ja die Geister. Habe jetzt bei Twitter viel ohne www gepostet. Prinzipiell sollten wir uns einfach für eine Variante entscheiden und dann die andere Variante per 301 Moved Permanently auf die gewählte Variante umleiten.

Gehört zu den Basics für #4 

Zum Nachlesen: http://serverfault.com/questions/145777/what-s-the-point-in-having-www-in-a-url

**Comment by lockeyo** [comment]
I think it's much more cleaner to have a url without www. I think the params before the actual name of the domain should be reserved for subdomains like community.roadgenius.de or something like that. I could create a move 301 if we have the same opinion.

**Comment by lorey** [comment]
I really don't care this much. If you want, you can already set up the forwarding :)

**Comment by lockeyo** [comment]
Done. Redirect to non www url

**Comment by lorey** [comment]
Nice, thanks :+1:
