### ISSUE TITLE
Change to private repo via GitHub Edu Pack

### ISSUE THREAD

**Issue by lockeyo** [lorey/roadgenius.de#8]
I would recommend to make this repo private, too. I want to extend this service to a plattform with a PHP Framework in the background for all the community stuff we have in our minds. If you don't mind i would like to use Laravel. If you want to have a password for laracast.com, i have one. There you can learn everything in just 3 hours and get right into awesome programming with a straight forward framework.

**Comment by lorey** [comment]
Yeah, I'm going to do this. Framework is another question to be discussed elsewhere.

**Comment by lockeyo** [comment]
Nice. Thanks. Yes, you're right. Sorry to mix this issue with an other topic.
